# Generated by Django 3.2.3 on 2021-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_auto_20210516_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
