# Generated by Django 3.2.3 on 2021-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_meeting_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meetingNotes',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='meeting',
            name='refMeet',
            field=models.IntegerField(default=0),
        ),
    ]
