# Generated by Django 3.2.3 on 2021-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_auto_20210517_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('taskGroup', models.CharField(default='', max_length=25)),
                ('description', models.CharField(default='', max_length=1000)),
                ('taskNotes', models.CharField(default='', max_length=2000)),
                ('refTask', models.IntegerField(default=0)),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
